### ISSUE TITLE
Refactor IaC scripts

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#101]
create-resources.bash has become a beast:
* it's getting harder to maintain as most of it is lumped into one giant script
* it's not straight forward to only re-build portions of the infrastructure

- [x] Can be used in the FNS environment.
- [x] Scripts no longer rely on global administrator role to run

**Comment by cjhskippy** [comment]
Flagging as a likely interest for sprint 3.  As we continue to add new skeletons of features, this is likely to only become more of a burden on productivity.  Might as well invest in it sooner if this is an ongoing source of toil.

**Comment by kingcomma** [comment]
This may be out of scope or this issue, but it could be worth researching ways to achieve some of the functionality of [complete mode](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deployment-modes) within our current approach to IaC. Primarily, as a developer, I would like a way for resources that are no longer part of our IaC to be removed whenever `create-resources` is run.

With our current setup where ARM templates are deployed to shared resource groups via several calls to `az deployment group create`, complete mode would be unworkable and removing a resource like an unused deployment slot on app service requires manual work.

**Comment by ryanhofdotgov** [comment]
https://github.com/18F/piipan/issues/101#issuecomment-745349820 spilt off into https://github.com/18F/piipan/issues/544

**Comment by ryanhofdotgov** [comment]
While there is still more refactoring and decomposition to be done, the referenced PRs above address the scope of this issue.
