### ISSUE TITLE
NAC Header includes USDA branding

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#1014]
As a State eligibility worker, I want visual cues to remind me where I'm working and that it's an official website.

All pages ( query, results page) include:
- [ ] [USDA signature lockup](https://www.usda.gov/digital-strategy/design-and-brand/plays#design3)

An example treatment:
<img width="533" alt="Screen Shot 2021-08-13 at 2 28 13 PM" src="https://user-images.githubusercontent.com/1299543/129420165-8420d196-8a36-4168-8419-62e15eff53d6.png">

**Comment by echappen** [comment]
@cjhskippy Is this task ok for me to start now, or did you want to hold off until #1125 is done?

**Comment by juliaklindpaintner** [comment]
@echappen I'd edit this issue to only include the first item:

All pages ( query, results page, lookup ID search, lookup results) include:
- [ ] USDA signature lockup

**Comment by cjhskippy** [comment]
@echappen @juliaklindpaintner I think this one is ready to go.  Good catch on the outdated content.

**Comment by cjhskippy** [comment]
Now a duplicate - was incorporated into #1379
