### ISSUE TITLE
Reconfigure Front Door on App Services, but with Easy Auth

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#1029]
In PR #1028, we enabled Easy Auth on the query tool dashboard and open up direct access to the App Service instances, going around front door.

Now, with some nudging in the right direction from Fast Track, [incorporate these settings](https://gsa-tts.slack.com/archives/C018P1ZJPEC/p1627074364005500), and restrict access to the query tool/dashboard to Front Door, reversing the relevant portions of PR #1028.

~This is required due to the nature of how Front Door functions – in short, using Easy Auth and Front Door together requires a custom domain/custom certificate. This is described in at least a couple of different places:~
* ~https://edi.wang/post/2020/6/29/solving-azure-ad-sign-in-failure-with-azure-front-door~
* ~https://vincentlauzon.com/2019/07/17/azure-app-service-authentication-with-azure-front-door/~

~After we obtain custom domains/custom certificates, restrict access to the query tool/dashboard to Front Door, reversing the relevant portions of PR #1028.~

**Comment by ryanhofdotgov** [comment]
Revisit this now that implementation has moved from AAD to OIDC, follow up with FastTrack to see if they were able to come up with a working example of this working without custom domains.

**Comment by timoballard** [comment]
Moving from AAD to OIDC does not appear to resolve this issue. Following up with FastTrack for next steps

**Comment by ryanhofdotgov** [comment]
Moving out to backlog, pending insight from FastTrack.

**Comment by ryanhofdotgov** [comment]
Closed by #1380 and #1381. New issue cropped up though: #1383
