### ISSUE TITLE
Semi-automated mechanism for establishing IdP secret for App Service instances

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#1039]
Semi-automated mechanism to set up App Service environment variable from that will come in a separate PR. Follow up to #1028.

Implementation notes:
- Design for future scenario where we have multiple load-balanced instances of the query tool (dashboard too, but that's less likely)
- If setting secret in CLI, don't pass secret via CLI parameter, use `read`, etc. ([like our AzCopy example](https://github.com/18F/piipan/blob/1284f25851be575128655324e51af92ac8bff7a1/etl/docs/uploads.md#azcopy))
- Maybe just a bash script that iterates over the dashboard or query tool instances using their SysTag (see approach elsewhere in script), then set the env variable with value collected at prompt? Run once for dashboard, a second time (second password) for query tool?

**Comment by ryanhofdotgov** [comment]
Implementation notes:
- Maybe just a bash script that iterates over the dashboard, query tool instances using their SysTag (see approach elsewhere in script), then set the env variable with value collected at prompt?

**Comment by timoballard** [comment]
@ryanhofdotgov - do you have thoughts on setting this up so that secrets are read out of a persistent key vault, where the name of the vault is configurable as part of IaC?
