### ISSUE TITLE
Change all app service instances to Windows-under-the-hood plans

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#1042]
Change all app service instances to Windows-under-the-hood plans:
- there are specific networking features/visualizations that aren't available in Linux-under-the-hood plans
- allows us to be consistent with how we deploy other components in the system (which we changed to Windows for similar lack-of-parity reasons)

**Comment by kingcomma** [comment]
Context on logging discrepancies between Windows and Linux plans: https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-diagnostic-logs
