### ISSUE TITLE
eAuth integration in FNS dev environment

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#1070]
Attempt to configure the FNS test environment's deployment to use eAuth as the OIDC provider.

- Reach out to FNS team to establish user roles / groups as needed
- Attempt to configure FNS dev to require eAuth for login

AC:
- [ ] ~FNS user with correct roles authenticates using eAuth~
- [ ] ~FNS user without correct roles cannot log in to dev environment~
- [x] dashboard protected by eAuth
- [x] query tool protected by eAuth

**Comment by ryanhofdotgov** [comment]
This ticket has been rescoped, as there is a process tail to establishing roles in eAuth. Will create follow-on tickets for discrete tasks.
