### ISSUE TITLE
Group 1A inquiries re: case actions

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#1071]
To inform designs for saving the action taken in response to matches, identify:

How do States structure their case action data?  Does it pose any potential for automation? 
- Do all 1A States track the case action for each individual in an application / household member addition / recertification? 
- What are the names of the case action resolutions at each state? 
  - Are there more options than just “certified”/”active” and “ineligible”? 
  - Are they generic (“ineligible”) or do they provide insight into the reason why an individual was ineligible? (“ineligible - already receiving SNAP”)

**Comment by erinzstrenio** [comment]
- [ ] Email questions to states and review during check-in calls
