### ISSUE TITLE
Spike: see how we can send Azure Policy events to Event Hub

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#1093]
Investigate if we can send Azure Policy events to Event Hub for consumption by an external SIEM, just like the resource logging described here:
https://github.com/18F/piipan/blob/dev/docs/log-streaming.md

**Comment by kingcomma** [comment]
Potentially relevant: https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/activity-log#send-to-azure-event-hubs

**Comment by kingcomma** [comment]
It appears this can be achieved in the Portal by going to Portal > Activity Log > Diagnostic settings. The available log categories are:

- Administrative
- Security
- ServiceHealth
- Alert
- Recommendation
- Policy
- Autoscale
- ResourceHealth

Presumably we want the `Policy` category, but that should be verified with research.

**Comment by kingcomma** [comment]
Adding diagnostic settings for activity log: https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/quick-collect-activity-log-arm?tabs=CLI#create-diagnostic-setting

**Comment by kingcomma** [comment]
Adding a diagnostic setting for the "Policy" category results in log messages like this being sent to our event hub when a policy assignment is triggered (i.e., a new resource is created and checked for compliance). I've obscured some IDs just to be safe:

```
{
    ...
    "level": "Warning",
    "properties":
    {
        "isComplianceCheck": "False",
        "resourceLocation": "westus",
        "ancestors": "",
        "policies": "[{\"policyDefinitionId\":\"...\",\"policySetDefinitionId\":\"...\",\"policyDefinitionReferenceId\":\"...\",\"policySetDefinitionName\":\"...\",\"policyDefinitionName\":\"...\",\"policyDefinitionEffect\":\"audit\",\"policyAssignmentId\":\".../Microsoft.Authorization/policyAssignments/cis-1_3-rg-core-tdb/\",\"policyAssignmentName\":\"cis-1_3-rg-core-tdb\",\"policyAssignmentScope\":\".../resourceGroups/rg-core-tdb\",\"policyExemptionIds\": ...}]",
        "eventCategory": "Policy",
        "entity": ".../resourcegroups/rg-core-tdb/providers/Microsoft.Storage/storageAccounts/mktesttriggerpolicy",
        "message": "Microsoft.Authorization/policies/audit/action",
        "hierarchy": ""
    }
}
```
