### ISSUE TITLE
Deliver Event Grid events to Metrics Collector using managed identity

### ISSUE THREAD

**Issue by kingcomma** [18F/piipan#1111]
Consistent with our zero-trust approach, deliver events from Event Grid to the Metrics Collector Function app using a managed identity.

- [ ] Configure Event Grid (see: https://docs.microsoft.com/en-us/azure/event-grid/enable-identity-custom-topics-domains)
- [ ] Enable app service authentication on Metrics Collector
- [ ] Log managed identity information when Metrics Collector is called

This ticket is an extension of #1055.

**Comment by kingcomma** [comment]
Turns out the required approach isn't as straightforward as what I outlined above. @ryanhofdotgov I'm a little stuck trying to figure out how best to achieve our goal of a zero-trust approach to Azure Functions with Event Grid triggers. Would you agree that the trade-offs outlined below are not acceptable? If so, is the current approach sufficient or should we research other options?

Using managed identities to delivery events (taking the same approach as we've taken with our HTTP triggered Function apps that run our APIs) requires two changes that don't feel like acceptable tradeoffs:

1. Switching the Function to an HTTP trigger and changing the Event Grid subscription to use a ["webhook" endpoint type rather than an "Azure Function" endpoint type](https://docs.microsoft.com/en-us/azure/event-grid/handler-functions)
2. Implementing custom application-level code that performs a [validation handshake with Event Grid](https://docs.microsoft.com/en-us/azure/event-grid/webhook-event-delivery#endpoint-validation-with-event-grid-events) (this step is handled automatically by Azure if using the "Azure Function" endpoint type)

As a reminder, the current approach we are taking for delivering metrics events to the metrics collection Function app is to:

1. Add an access restriction on the Function app that limits inbound traffic to the `AzureEventGrid` service tag
2. Let Event Grid do it's [built-in behavior](https://docs.microsoft.com/en-us/azure/event-grid/security-authentication#:~:text=Access%20keys%20are%20fetched%20using%20Event%20Grid%20service%20principal%27s%20credentials.%20The%20permissions%20are%20granted%20to%20Event%20Grid%20when%20you%20register%20the%20Event%20Grid%20resource%20provider%20in%20their%20Azure%20subscription.) of grabbing the Function's baked-in access key and using it to authenticate event delivery

**Comment by ryanhofdotgov** [comment]
Some follow up in [our Slack discussion](https://gsa-tts.slack.com/archives/C018P1ZJPEC/p1626973487045400?thread_ts=1626973069.044300&cid=C018P1ZJPEC). 

@kingcomma How about writing up a short ADR around your comment above re: keeping current approach to close this issue out?
