### ISSUE TITLE
Remove `lookup_id` from `MatchQueryResponse` in per-state API OpenApi schema

### ISSUE THREAD

**Issue by kingcomma** [18F/piipan#1113]
The per-state API schema currently claims to return a `lookup_id` property. The `lookup_id` is only returned by the orchestrator API and not the per-state API.

This issue may become irrelevant after anticipated API refactoring.

<img width="668" alt="Screen Shot 2021-06-28 at 11 19 25 AM" src="https://user-images.githubusercontent.com/3246955/123668770-70943b00-d809-11eb-9ceb-4ef6b14708d6.png">

**Comment by cjhskippy** [comment]
Closed in connection with removal of Lookup API.
