### ISSUE TITLE
Extract OIDC claims/user info for display and logging in the dashboard

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#1126]
Using the information conveyed to the dashboard through its configured identity provider and Easy Auth OIDC mechanism:
- extract out the currently signed in user's email address and display in upper right corner of application, to the left of the sign out link
- extract out all the claims of the currently signed in user and log it to the App Service log at the `INFO` level

Implementation notes:
- Reference: [Work with user identities in Azure App Service authentication](https://docs.microsoft.com/en-us/azure/app-service/configure-authentication-user-identities)
- Will likely need to use [MaximeRouiller.Azure.AppService.EasyAuth](https://github.com/MaximRouiller/MaximeRouiller.Azure.AppService.EasyAuth)
- Follow on work is to [add same functionality to query tool](#1127)

**Comment by timoballard** [comment]
@ryanhofdotgov - Have you thought about how often we want to log user claims? (e.g. on every request or just once after authentication)?

**Comment by ryanhofdotgov** [comment]
@timoballard Since it doesn't seem like we have access to Easy Auth logs, I think logging all the claims just once, after authenticated, makes sense and reduces log noise.

We should log the username (email address) of the user on each HTTP request though.
