### ISSUE TITLE
Remove variable $METRICS_RESOURCE_GROUP from IAC scripts

### ISSUE THREAD

**Issue by echappen** [18F/piipan#1155]
This resource group is deprecated. To eliminate confusion, we can remove its name from the IAC scripts and use $RESOURCE_GROUP in its place. 

_Originally posted by @echappen in https://github.com/18F/piipan/pull/1154#discussion_r664605773_

**Comment by timoballard** [comment]
@echappen - closing because I just noticed there's an issue in this sprint's stretch goals that captures this work

https://github.com/18F/piipan/issues/1025
