### ISSUE TITLE
Spike: plan per-state API removal

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#1229]
We've had discussions on removing the per-state internal API layer and replacing it with direct PostgreSQL access by the Orchestrator. [Slack discussion thread](https://gsa-tts.slack.com/archives/C018P1ZJPEC/p1623875385039100?thread_ts=1623874843.038000&cid=C018P1ZJPEC).

Draw up a more detailed implementation plan for removal, considering the additional database-level security mechanisms described in above thread.

**Comment by kingcomma** [comment]
Draft removal plan below. Is this the level of detail we were hoping for?

- [ ] Create read-only role in each per-state database for orchestrator's system-assigned identity (possibly using same approach as in [`create-core-databases.bash`](https://github.com/18F/piipan/blob/fa0a46428e06180eb7cd8474e14409f67e5d8b6d/iac/create-core-databases.bash#L247-L250)). May require changing when certain resources are created by the IaC.
- [ ] Bind each per-state database to the orchestrator function app using an environment variable.
- [ ] Update orchestrator application to connect to each per-state database using a system-assigned identity and query for each person in a household request.
- [ ] Update documentation to reflect new operating state.
- [ ] Remove any dangling infrastructure, configuration, docs, files (e.g., per-state function apps, environment variables, service principals, API specs).

**Comment by ryanhofdotgov** [comment]
👍 – wanted just enough break down so it would be possible to do a rough level of effort estimate for https://github.com/18F/piipan/issues/1339 – what are you thinking there?

**Comment by kingcomma** [comment]
It seems reasonable to say about a day for the IaC changes, maybe two days for the application changes, and another day for the clean up tasks (which could be split off into follow ups). We have four days left in the sprint, so at least I should be able to make good progress on this (I'm planning to break it into several PRs) and at best it's possible I could finish it up.
