### ISSUE TITLE
1-2 page plain language PPRL summary

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#1451]
Goal: 
Pretend like we're starting from scratch - how we go from a state providing information to the NAC preventing duplicate participation.

Also help understand what PII states are sending, how matches occur with "deidentified" PII

(this is not a summary of what's different in the current approach vs. what we did before)

**Comment by juliaklindpaintner** [comment]
[Plain language guide to the PPRL approach](https://docs.google.com/document/d/1WpcnkJNUtlWtwDZhW8PznehWHVNKw8MHeKCjq709jxA/edit#heading=h.aysn3jmnify) has been created and shared.
