### ISSUE TITLE
Modify match db integration tests to use the real DDL

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#1492]
As a developer, I want my db integration tests to reflect the actual database schemas used in production to catch errors in the DDL earlier.

Currently Piipan.Match.Orchestrator.IntegrationTests duplicates the DDL for the ETL database:
https://github.com/18F/piipan/blob/eaef1ef3654002079fd8afe9098ded22457dac45/match/tests/Piipan.Match.Orchestrator.IntegrationTests/DbFixture.cs#L83

This needs to instead load ddl/per-state.sql directly. Also see https://github.com/18F/piipan/pull/1489#discussion_r699478814

**Comment by kingcomma** [comment]
This is also referenced in #1459

**Comment by kingcomma** [comment]
Closed via #1511
