### ISSUE TITLE
Design spike: Match lookup and disposition / resolution

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#1548]
Assess how users will:

- Look up a prior, open match.  Also assess how users will proceed to do one of these things with the match:
  - See whether the individual involved in the match is vulnerable / needs their location protected
  - Flag the match as invalid (see issue #300)
  - Report their state's decision on eligibility (see issue #1547)
- Navigate the site.  We're assuming that there is good reason to have different forms to perform a query (enter name, DOB, SSN) vs. look up a previous match (enter a match ID).  If that's the case, we will need to decide:
  - Which function is the default when you reach the NAC (or neither)
  - How to navigate from the home page to perform a query
  - How to navigate from the home page to look up a prior match
  - How to navigate from query / prior match back to home page
  - Whether direct navigation from query / prior match lookup pages to each other should be possible + how this works

AC: 
- [x] Rough wireframes show each of the above interactions
- [ ] Review wireframes with team
- [ ] Explore alternatives
- [ ] Refine wireframes

**Comment by cjhskippy** [comment]
@juliaklindpaintner mea culpa - I should have included this bullet point in the original AC.  No worries if this one doesn't get into this sprint's version of the wireframes: `See whether the individual involved in the match is vulnerable / needs their location protected`

**Comment by juliaklindpaintner** [comment]
@cjhskippy I think I met the original AC for this within [the storyboard](https://app.mural.co/t/gsa6/m/gsa6/1631737658002/10d730226e10fbd22723ebf57979333b110f4856?sender=julialindpaintner1638) but would like more time to explore and refine. Looking forward to reviewing and getting your thoughts!
