### ISSUE TITLE
Spike: Testing strategy

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#1558]
Research strategies to implement tests that will bring the Piipan codebase closer in line with the 90% code coverage that we want as a baseline before handing off development.

- [x] service registration testing (see comment below)

**Comment by ryanhofdotgov** [comment]
As part of this work, be sure to [include service registration testing as outlined here](https://github.com/18F/piipan/issues/1445#issuecomment-915351590), making sure that we do not exclude code from test coverage [like this example](https://github.com/18F/piipan/blob/369900c8da0ccd73dcd741cdee6f9500431f3c63/query-tool/src/Piipan.QueryTool/Startup.cs#L18)

**Comment by ryanhofdotgov** [comment]
@timoballard Are there any conclusions that can be written up from the spike – even just a comment, if not worthy of an ADR?

**Comment by timoballard** [comment]
@ryanhofdotgov - yes, absolutely. Apologies, was cleaning up tasks as the sprint was winding down and forgot to come back to this. I think an ADR for the testing approach with respect to the standard project setup makes sense - I'll add a card
