### ISSUE TITLE
Let user know API call has failed in dashboard

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#1567]
If the API call made by the dashboard fails, the user is not informed that something has gone wrong. The exception is only logged when caught:
https://github.com/18F/piipan/blob/369900c8da0ccd73dcd741cdee6f9500431f3c63/dashboard/src/Piipan.Dashboard/Pages/ParticipantUploads.cshtml.cs#L56

Expected behavior:
Some type of error message is displayed to end user

**Comment by kingcomma** [comment]
Closed by https://github.com/18F/piipan/pull/2035
