### ISSUE TITLE
Create ADRs for initial implementation choices

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#16]
- [x] .NET Core
- [x] Azure
- [x] Azure Database for PostgreSQL
~- [ ] Azure Blob Storage~
~- [ ] Azure Functions~

Reference: https://adr.github.io/

**Comment by kingcomma** [comment]
@ryanhofdotgov Do you have a preference for the format of these ADRs? Both [MADR](https://github.com/adr/madr/blob/master/template/template.md) ([example](https://github.com/transcom/mymove/blob/master/docs/adr/0000-server-framework.md)) and the [Nygard format](https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions.html) ([example](https://github.com/HHS/Head-Start-TTADP/blob/main/docs/adr/0007-use-plantuml-for-diagrams.md)) look good to me.

**Comment by ryanhofdotgov** [comment]
We've decided to go with the Nygard format. I started using [adr-tools](https://github.com/npryce/adr-tools), but you could create ADRs easily without it.
