### ISSUE TITLE
Redirect logged-out users to intended destination after successful login

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#1718]
As a state agency worker handling my first match of the day, I want the following experience when I click a match URL link:
- The NAC makes me log in
- After getting logged in, I want to be redirected to the original URL destination.  I don't want to get sent to the NAC home page and have to go click the original link from my notification email again.

AC:
- [ ] When a logged-out user clicks a match URL link, they are sent to the login page.  Upon successful login, they are redirected to the original destination URL.

**Comment by ryanhofdotgov** [comment]
I think this should already be happening, but if not, it is likely related to this setting in the dashboard and query tool:
https://github.com/18F/piipan/blob/646ef334d717d353c408b56009243fe2afeefcdd/iac/arm-templates/dashboard-app.json#L225
