### ISSUE TITLE
Update CSV schema to make `lds_hash` a required field

### ISSUE THREAD

**Issue by kingcomma** [18F/piipan#1722]
Currently the `lds_hash` field is constrained only by a regex pattern. Consequently, a row that contains no value for `lds_hash` will pass validation. This is in conflict with the BulkUpload function app which will throw exceptions for rows with no value for `lds_hash`.

Update `import-schema.json` with a `"required": true` constraint.

**Comment by cjhskippy** [comment]
Maybe also `"unique": true` to block states from accidentally inserting more than one record for the same person?

**Comment by ryanhofdotgov** [comment]
It's extremely unlikely (understatement), but theoretically possible for a hash collision to occur. Participant id could be flagged as unique though.

**Comment by cjhskippy** [comment]
That might be a good call.  I think there are some reasonable scenarios where states will incorrectly generate hash collisions - if they neglect to filter out individuals without a SSN for example.  Given that we can't safely flag the hash as unique, maybe it would be better at a future stage to build in warnings if we see duplicate hashes from a state.
