### ISSUE TITLE
Prioritize open research questions

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#175]
Document outstanding research questions and prioritize which questions to focus on in the next round of interviews.

- [x] Connect with PM on research priorities for product decisions
- [x] Outline top 3 research priorities in this issue

**Comment by juliaklindpaintner** [comment]
We have research questions documented in several places, but there is a running list in Issue #104. After connecting with Skippy, we agreed that our research priorities at the moment are as follows: 

1. Research that will help us recruit first round state partners
2. Research with existing NAC pilot states (including assessing whether they would be interested in being first round state partners, whether we can leverage documentation from the pilot, and ensuring we capture best practices/lessons learned beyond the pilot report)
3. Research that will help us clarify the intended workflow for state workers after a NAC match
