### ISSUE TITLE
ParticipantDao is not reusing database connections

### ISSUE THREAD

**Issue by kingcomma** [18F/piipan#1831]
This issue was discovered while running match queries. Each time a query is run, new database connections are opened but not closed. Eventually, when connections exceed the default PostgreSQL limit of 150, this results in the following error being returned by the API:

```
{
    "errors": [
        {
            "status": "500",
            "title": "PostgresException",
            "detail": "53300: remaining connection slots are reserved for non-replication superuser connections"
        }
    ]
}
```

The culprit appears to be [this line](https://github.com/18F/piipan/blob/dev/participants/src/Piipan.Participants/Piipan.Participants.Core/DataAccessObjects/ParticipantDao.cs#L26) (and other similar lines across our DAOs). Because the connection is not wrapped in a `using` statement or explicitly closed with `connection.Close()`, it appears it is not properly disposed. This issue is especially pronounced when querying the match API for multiple persons at one time — if a single request contains ~15 people it will exceed the connections limit in a single run.

A potential fix is changing the `IDbConnectionFactory.Build` to return and unopened instance of `DbConnection` and then update the DAO methods accordingly:

```
using (var connection = await _dbConnectionFactory.Build(state))
{
    await connection.OpenAsync();
    [...]
}
```

Any fixes should be applied to all DAOs:
- [ ] `Piipan.Participants.Core.DataAccessObjects.ParticipantDao`
- [ ] `Piipan.Participants.Core.DataAccessObjects.UploadDao`
- [ ] `Piipan.Match.Core.DataAccessObjects.MatchRecordDao`

**Comment by ryanhofdotgov** [comment]
Be sure to understand how connection pooling works in .NET as this work gets picked up.
