### ISSUE TITLE
SSL certificate

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#1946]

**Comment by ryanhofdotgov** [comment]
See Slack messages:
- https://gsa-tts.slack.com/archives/C018P1ZJPEC/p1635871491045100
- https://gsa-tts.slack.com/archives/C018P1ZJPEC/p1635871521045900

**Comment by ryanhofdotgov** [comment]
@timoballard @kingcomma Also see FNS NAC Architecture –> General -> Files -> Custom domains and certs.docx.
