### ISSUE TITLE
(Spike) Research implementation strategy for payload encryption

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#2018]
We expect that both #1594 and #1595 will be required prior to accepting any real participant data.  Of these two issues, #1595 is the most urgent, as it will change the APIs / development expectations for state agencies.

This task is to define our implementation strategy for message-level encryption.  We'll want to specify:
- how the public + private keys will be stored
- how states will access their key
- verify that the proposed solution is compatible with FIPS 140-2 requirements
- how states can test interim states (e.g. still test that their pre-encryption payloads are successfully normalized + formatted)

**Comment by ryanhofdotgov** [comment]
FIPS 140-2 concerns should be solved by using Key Vault to perform encryption: https://github.com/18F/piipan/issues/1949

**Comment by kingcomma** [comment]
See [initial research notes](https://docs.google.com/document/d/1Xurzv2pGdy4IPsdAy_TWJPQ9MnZhjh1i9asPfAmt6_4/edit#).
