### ISSUE TITLE
create-resources frequently fails on match API creation

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#204]
Publishing the initial version of per-state match function to its function app will frequently fail if the function app was created immediately before:
https://github.com/18F/piipan/blob/5620c35abd850e09e8f57a33a749323ad7f54ba0/iac/create-resources.bash#L337

We believe this is a timing/replication issue; i.e., [creating the deployment group returns before it is actually completely created across the cloud](https://github.com/18F/piipan/blob/5620c35abd850e09e8f57a33a749323ad7f54ba0/iac/create-resources.bash#L320). We don't see the same failure patterns on [the first publication of the ETL function](https://github.com/18F/piipan/blob/5620c35abd850e09e8f57a33a749323ad7f54ba0/iac/create-resources.bash#L287).

This could be because of the way it splits up the function app creation, or because there are enough intermediate processing steps in between that it hides the issue.

We could try:
* sleep hack – just add 10-20 seconds of waiting
* split into 2 loops, one to create function app, another to publish
* explicitly querying the function app list in a loop before proceeding (assuming that presence in the list implies ability to publish):
`az functionapp list --resource-group piipan-match --query "[].defaultHostName"`

**Comment by kingcomma** [comment]
For reference, the Azure CLI tools take the sleep-and-loop approach in at least one similar instance (creating role assignments): https://github.com/Azure/azure-cli/blob/master/src/azure-cli-core/azure/cli/core/commands/arm.py#L1086

**Comment by ryanhofdotgov** [comment]
Also see: https://github.com/Azure/azure-functions-core-tools/issues/1766, https://github.com/Azure/azure-functions-core-tools/issues/1616

**Comment by ryanhofdotgov** [comment]
We don't have this problem any more as we simply added a 60 second wait before (almost) every function app publish command.
