### ISSUE TITLE
Values of identifierUris property must use a verified domain of the organization or its subdomain

### ISSUE THREAD

**Issue by edwintorres** [18F/piipan#2289]
Error when running the IaC process in a new environment. 

```
configure Easy Auth for OrchestratorApi and QueryApp
ERROR: Values of identifierUris property must use a verified domain of the organization or its subdomain: 'https://tts-func-orchestrator-eth2.azurewebsites.net'
```
According to [Microsoft documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-breaking-changes#appid-uri-in-single-tenant-applications-will-require-use-of-default-scheme-or-verified-domains) AppId Uri in single tenant applications will require use of default scheme or **verified domains** 

The change does not affect existing applications using unverified domains in their AppID URI. It validates only new applications or when an existing application updates an identifier URIs or adds a new one to the identifierUri collection. 
Effective date: October 2021.

**Comment by kingcomma** [comment]
Any changes to our implementation due to this issue should be reflected in https://github.com/18F/piipan/blob/dev/docs/securing-internal-apis.md

**Comment by kingcomma** [comment]
When creating a new app registration by enabling App Service Authentication, Azure now defaults to setting the application ID URI as `api://<app-id>` rather than the previous default of `https://<resource-name>.azurewebsites.net`. Mimicking this approach may be a solution that does not require verified domains.
