### ISSUE TITLE
Enforce rate limiting for APIM

### ISSUE THREAD

**Issue by kingcomma** [18F/piipan#2301]
Rate limiting is not currently configured for queries to the duplicate participation API. Rate limiting needs to be enforced at two points:

- The APIM level, via a [per-subscription policy](https://docs.microsoft.com/en-us/azure/api-management/api-management-access-restriction-policies#LimitCallRate)
- ~The Query Tool level, which connects directly to the orchestrator and would not be covered by an APIM policy, likely via a [WAF rule on the Front Door instance](https://docs.microsoft.com/en-us/azure/web-application-firewall/afds/waf-front-door-rate-limit-powershell) (should be confirmed with some research).~ See #2345 

The appropriate rate limit can be a rough estimate based on expected volume that is refined over time. Different rates will likely be appropriate for different states. If that complexity is difficult to implement with this ticket, it can be deferred to a subsequent sprint.

See "Lack of API Rate Limiting on API and Query Tool" in security issues tracker.

**Comment by edwintorres** [comment]
This was close with [Eth/issue 2301 set rate limit #2327](https://github.com/18F/piipan/pull/2327) is I'm not wrong.
