### ISSUE TITLE
Permitted ciphers

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#2317]
Identify required actions related to "weak ciphers enabled" feedback

Note: don't expect this to be resolved this sprint, but we do want to start the conversation.

**Comment by echappen** [comment]
From manual testing report: 

> RSA with AES 128 has been identified which is a weak cipher.

This was found on both the Dashboard and Query Tool apps.

First, we should confirm that of the 4 ciphers these apps support (and which the report found), the particular ones deemed as weak are the ones marked here:
* TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 <-- weak
* TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
* TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 <-- weak

Microsoft documentation [states](https://docs.microsoft.com/en-us/azure/frontdoor/concept-end-to-end-tls#supported-cipher-suites) that for TLS1.2, the four ciphers above are the ones supported out of the box.

However it doesn’t seem like we can customize our cipher list through Front Door. Also from the [docs](https://docs.microsoft.com/en-us/azure/frontdoor/concept-end-to-end-tls#supported-cipher-suites):

> Azure Front Door doesn’t support configuring specific cipher suites. You can get your own custom TLS/SSL certificate from your Certificate Authority (For example: Verisign, Entrust, or DigiCert). Then have specific cipher suites marked on the certificate when you generate it.

So I think we'll need to confirm whether these ciphers are really ok or not, and if not, that a custom TLS/SSL cert is the plan of action we want to take. 

I'm unaware of alternatives other than switching from Azure Front Door.
