### ISSUE TITLE
Collaboration API exposes match details to frontend

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#2381]
In order to enable #1656 , our internal API needs to provide the match details to the frontend.  This issue is to create the working API endpoint - we will likely need to complete #1940 first.

AC: 

- [ ] Match API accepts the unique match ID and returns outputs listed in #1940
- [ ] API returns an appropriate response if there is no match corresponding to the given match ID 
- [ ] API returns an appropriate response for malformed inputs
- [ ] API is only available to internal Piipan functions / apps

**Comment by kingcomma** [comment]
Small nit: internally, this functionality should be part of the "collaboration API" which we have on our architecture diagrams but have not yet created. If/when this functionality is exposed externally, it may fall under the external-facing duplicate participation (aka match) API.
