### ISSUE TITLE
Revisit Azure resource naming conventions

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#252]
We need to support multiple, non-production deployment environments within a single subscription. Revisit our resource naming conventions, group names, access control, etc. to support multiple deployment environments.

As we revisit how we identify our resources, keep [Microsoft's recommended practices in mind](https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming).

**Comment by ryanhofdotgov** [comment]
Also: adhere to [partner agency decision/discussion here](https://docs.google.com/document/d/1m4esX7gtH2SXrpUz0j_JKJRLSoOwjLoxJlBokXWkWHU/edit#).

**Comment by ryanhofdotgov** [comment]
Also see:
https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules

**Comment by echappen** [comment]
@ryanhofdotgov  Are we dropping the name "piipan" once we move into the partner's Azure environment? (referencing [this spreadsheet](https://docs.google.com/spreadsheets/d/1pYdvVoICjQjx9RvyYhuoV8D0xCrVRRQzYNhpdNvFsyc/edit#gid=1351188795))

For example: `piipan-metrics` would become `fns-rg-metrics-dev`

**Comment by ryanhofdotgov** [comment]
That's right – the goal is to keep Piipan the project somewhat separate from its corresponding instance at the partner agency in order to help maximize reuse in the future for other benefit programs.

I think that means:
* allowing a configurable prefix for resources
* allowing our resource groups to be named differently, and configured external to the main scripts
* dropping "piipan" when we don't need it for disambiguation to keep names short; i.e., everything in the subscription is piipan.

So I am anticipating a set of infrastructure config files for TTS dev/TTS test/partner dev/partner test/partner preprod/partner prod. We may just keep the partner config files just in the partner source code control system.

**Comment by ryanhofdotgov** [comment]
Good chunk of this work was completed in #442, #408 and the yet-to-be-merged PR #451.

Don't finalize until we incorporate lessons from deploying to Azure Government.
