### ISSUE TITLE
Warn when API rate limits are approached

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#2530]
Publicly-facing API endpoints have rate limits to prevent denial-of-service attacks.  However, there is always a possibility that legitimate use will exceed the volume of traffic that we anticipate.

In order to protect against service disruptions, we may want to institute some sort of notification to let administrators know when a rate limit has been approached.

**Comment by kingcomma** [comment]
Be aware, Azure API Management's default configuration is to return the following error messaging when a rate limit has been surpassed:

```
{
    "statusCode": 429,
    "message": "Rate limit is exceeded. Try again in ## seconds."
}
```

A `Retry-After` header is also included in the response.

**Comment by kingcomma** [comment]
For clarification, APIM rate limiting is implemented as a mitigation against brute-force attacks that could arise from mishandled credentials. I.e., prevent an attacker who gains access to a state's credentials from performing a dictionary attack.

We rely on [Azure's built-in "DDoS Protection Basic"](https://docs.microsoft.com/en-us/azure/security/fundamentals/ddos-best-practices#ddos-protection-basic) for denial-of-service protection.
