### ISSUE TITLE
Useful images are broken

### ISSUE THREAD

**Issue by beechnut** [18F/piipan#2676]
I'm reading the README to understand how this project works, but all of the images in the README and all the images in [docs/diagram](https://github.com/18F/piipan/tree/dev/docs/diagrams), [and here](https://github.com/18F/piipan/blob/dev/docs/pprl-plain.md), etc., are broken.

I'm trying to assess whether this might be a useful tool for another FNS engagement, and I think by not being able to see the diagrams, I'm missing out on an important avenue to understanding the project.

Would it possible to easily restore those, relatively soon?

**Comment by kingcomma** [comment]
@beechnut Weird! All images should be loading properly. Everything appears ok on my end when I load up our docs:

<img width="927" alt="Screen Shot 2022-02-08 at 9 56 33 AM" src="https://user-images.githubusercontent.com/3246955/153013256-f83f8346-44ff-40ee-a093-265c52c77273.png">

Can you confirm whether or not the raw GitHub URLs load for you?

- https://raw.githubusercontent.com/18F/piipan/dev/docs/diagrams/combine-and-deidentify.png
- https://raw.githubusercontent.com/18F/piipan/dev/docs/diagrams/daily-snapshots.png

**Comment by beechnut** [comment]
The images are unexpectedly being blocked by security software and not an issue with the repo, so I'm closing the issue.
