### ISSUE TITLE
Organize feasibility assessment process

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#279]
Produce a draft of the process we'll use for feasibility assessments with the states that raise their hands as interested.

- [x] Outline process we'll use for feasibility assessments
- [x] Draft conversation guide for feasibility assessments
- [x] Share process and guide with FNS for input
- [x] Draft communications/materials to be sent to volunteering states ahead of session
- [x] Review and finalize comms/materials to be sent to volunteering states ahead of session

**Comment by juliaklindpaintner** [comment]
I have a [draft of this going in Google docs](https://docs.google.com/document/d/1hCr6imbOUIndYT-QSqIRwLd7xqnVUlrzw4Glmi0ZWtc/edit#heading=h.26chu53sjgww)
