### ISSUE TITLE
Set vnetRouteAllEnabled to True in ARM template

### ISSUE THREAD

**Issue by echappen** [18F/piipan#2828]
*Todo (non-blocking):* When this integration is done, we will want to update the Function app's ARM template with `"vnetRouteAllEnabled": true` to restrict outbound traffic (since the API is only internal for now).

_Originally posted by @kingcomma in https://github.com/18F/piipan/pull/2824#discussion_r823043948_

**Comment by kingcomma** [comment]
Closed by #2831
