### ISSUE TITLE
Create API exception handling middleware for API's

### ISSUE THREAD

**Issue by echappen** [18F/piipan#2842]
Thought: Along the same lines as my logging comments, we could consider introducing API exception handling middleware (in another ticket) to that handle generic errors like NotFound & InternalServer exceptions.

_Originally posted by @bgfoshay in https://github.com/18F/piipan/pull/2829#discussion_r824874585_

**Comment by cjhskippy** [comment]
See NAC-493 to follow this thread in the updated backlog

**Comment by cjhskippy** [comment]
Closing since this has been incorporated into the current backlog.
