### ISSUE TITLE
Allow states to set disposition data back to null

### ISSUE THREAD

**Issue by echappen** [18F/piipan#2856]
Match Resolution API Add Event endpoint should allow inserting null values for fields that have already been set. For example, if a state wants to remove their `protect_location` flag. 

See thread:
_Originally posted by @bgfoshay in https://github.com/18F/piipan/pull/2848#discussion_r830389770_

**Comment by echappen** [comment]
Looking into this more, I don't think we currently have disposition data that should be set back to null:

| property | type | |
| --- | --- | --- |
| `protect_location` | boolean | once set by state, it can be reversed from false -> true or vice versa |
|  `invalid_match` | boolean | same as above |
| `initial_action_at` | timestamp | once set by state, can be changed to another date but shouldn't be removed |
| `final_disposition` | text | once set by state, cannot be changed or removed |

 Null values should indicate data that a state has never provided. 
 
 If we ever add disposition data that can be nullified, then this will become relevant.

**Comment by cjhskippy** [comment]
We've verified that the frontend handles unsetting values where appropriate. Since there is no direct API exposure, we can close this.
