### ISSUE TITLE
Get Azure tools on FNS laptops

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#337]
Get approval for 18F developers to use Azure tools on their FNS laptops, and then install the software that is needed.

Installations done for
- [x] Ryan
  - [x] Visual studio code
  - [x] Git
- [x] Michael
  - [x] Visual studio code
  - [x] Git

(Moved Matt + Eleni's install to #477, since they are still waiting on laptops)

**Comment by ryanhofdotgov** [comment]
In progress... initial notes on process is on Teams and[ mirrored here](https://drive.google.com/file/d/1iaIAhmNMNdftCoWxxzl9d_cL6yz_Yi07/view?usp=sharing)

**Comment by kingcomma** [comment]
Tools have been installed on my computer. I updated the mirrored doc with a couple notes from my experience.
