### ISSUE TITLE
Incorporate Azure Front door for query tool, dashboard

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#390]
As a system owner, I want piipan's web applications to have a security layer to help prevent common web attacks, including Cross-site Scripting (XSS) and SQL injection.

Incorporate Azure Front door in front of the query tool and dashboard, using it's default Web Application Firewall (WAF) rule set:
- [ ] query tool
- [ ] dashboard

**Comment by echappen** [comment]
@ryanhofdotgov There are two modes for WAF: Detection and Prevention. I'm assuming we'd wanted Prevention here?

**Comment by ryanhofdotgov** [comment]
Yeah, if we are using the default WAF rule set, Prevention is a good choice. 👍 

If we were experimenting with new WAF rules or if we had anything beyond the basic Razor app, you might want to run the rules in Detection mode for a while to see if they were inadvertently tripped by normal usage.
