### ISSUE TITLE
Spike: evaluate Azure Defender for App Service 

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#393]
Understand how Azure Defender for App Service brings benefits to our particular PaaS-centric approach fro web apps, and whether or not there is utility in applying it to Azure Functions.

Understand how this feature intersects with other App Service security layers (i.e., Front Door and API Management).

**Comment by cjhskippy** [comment]
Flagging as likely irrelevant now.

**Comment by ryanhofdotgov** [comment]
> Flagging as likely irrelevant now.

Can you say more?

**Comment by cjhskippy** [comment]
Per discussion, keeping this around.  I was mistaken about whether this was covered by research and development in the last few months.
