### ISSUE TITLE
Convert Metrics Database authentication to managed identity

### ISSUE THREAD

**Issue by echappen** [18F/piipan#409]
In order to keep our database resources more consistent, we should convert the metrics database to use a managed identity instead of the current admin username and password.

**Comment by kingcomma** [comment]
Steps involved:

- [ ] Metrics Collector
  - [ ] Activate system-assigned identity in IaC
  - [ ] Add database role for identity in IaC
  - [ ] Update application to use identity when connecting to database
- [ ] Metrics API
  - [ ] Activate system-assigned identity in IaC
  - [ ] Add database role for identity in IaC
  - [ ] Update application to use identity when connecting to database
- [ ] Remove Key Vault permissions from IaC for both Functions

**Comment by kingcomma** [comment]
@ryanhofdotgov This work consists of creating two roles in the the `core` database: one for the Metrics Collector's system-assigned identity and one for the Metrics API system-assigned identity. That's about where I hit the limits of my knowedge on roles and privileges in PostgreSQL. Do we want to follow a similar approach to privileges as we do in [`create-database.bash`](https://github.com/18F/piipan/blob/dev/iac/create-databases.bash#L40)?

**Comment by ryanhofdotgov** [comment]
Similar in the broad strokes, but perhaps a little bit more granular? Perhaps:
 - a database `metrics` owned by `metrics` role (or whatever it is called already)
 - grant Metrics API role just read access (https://stackoverflow.com/a/762649, `GRANT...ALL TABLES IN SCHEMA...`)
 - grant collector role read/write, without admin access (e.g., SELECT, INSERT, UPDATE, DELETE, and TRUNCATE)

There may be some differences in how the metrics uses schemas vs the participants records (e.g., `public` vs custom one)
