### ISSUE TITLE
Reject rows missing a first name

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#445]
The NAC will require a first name for any matching to be performed.  We should update the bulk upload API and related documentation to reject these rows.

This is not strictly MVP material.  Rejecting these rows and flagging them for FNS to learn about where data gets messy is valuable, but will not impact any match results.

- [ ] Bulk upload rejects rows that do not include a first name
- [ ] Bulk upload provides error message with reason for rejecting rows missing a first name
- [ ] Bulk upload API documentation is updated
- [ ] Update examples, see https://github.com/18F/piipan/pull/951#discussion_r643343415

**Comment by kingcomma** [comment]
@cjhskippy I was looking into issues around handling first names and saw this was closed by me 14 days ago. I think that was by accident and this should be reopened. Does that sound right to you?

**Comment by cjhskippy** [comment]
No longer relevant.  Now that the NAC performs matches against a deidentified participant hash and avoids collection of PII, this can be closed.
