### ISSUE TITLE
Query and dashboard website: Debug logging for API interactions

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#478]
As a developer, I would like to be able to deploy the query tool and dashboard to new environments, configure debug/trace level logging, and be able to see a trace of the execution so I can more easily identify where things are breaking.

- query tool
  - [x] API error messages are saved in logs that can be reviewed by Piipan developers
  - [x] Error messages for queries do not record PII
 - dashboard
   - [x] API error messages are saved in logs that can be reviewed by Piipan developers
   - [x] Error messages for queries do not record PII

**Comment by ryanhofdotgov** [comment]
@heymatthenry I updated the title and acceptance criteria checkboxes to match the original issue description which included both the query tool and the dashboard in its scope. We can also split up and schedule for next sprint if you'd prefer that.

**Comment by heymatthenry** [comment]
@ryanhofdotgov Nope, happy to finish this up in this sprint.
