### ISSUE TITLE
Consistent look for metrics dashboard

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#479]
As a FNS business owner, I want the metrics dashboard to be easy to navigate so that I can quickly see the difference between elements like headers, body text, and links.

- [x] Page header has similar look to query tool
- [x] Text is clearly differentiated
- [x] Link to the existing metric (most recent upload) is easily discerned

**Comment by heymatthenry** [comment]
@cjhskippy Just want to be clear about the 3rd AC here: putting aside the "hello world" text, which we can change whenever there's real text to put there, is this sufficient?
![image](https://user-images.githubusercontent.com/6290/111637568-ed0d8b80-87cf-11eb-93ba-0e4484be501f.png)

**Comment by cjhskippy** [comment]
@heymatthenry Just checked it off - that's pretty clearly a link to my eyes.
