### ISSUE TITLE
Develop the spec for the Match ID Lookup API

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#482]
Provide specifications for the Match ID Lookup API that provide enough information for a developer to work against (for example, the query website)

- [ ] Specify allowed inputs
- [ ] Expected outputs
- [ ] Add markdown page linking to API specs to Piipan docs

**Comment by echappen** [comment]
If we're doing this RESTfully, then a match ID lookup url would end in something like `/match_id/:id` where `:id` is the match ID to be queried.  Looking at #452 I'm assuming an ID would be url-safe. Let me know if this is a wrong assumption, or if a different url is preferred.
