### ISSUE TITLE
Update language in NAC Query website

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#571]
Change "Search for dual enrollments" to language that does not already assume duplicate participation & adheres to preferred nomenclature.

- [x] Draft new phrasing ("Search for SNAP participants")
- [x] Share with FNS program team / get approval
- [x] Update query tool website

**Comment by juliaklindpaintner** [comment]
@cjhskippy I've been thinking about this and it's tricky! In my wireframes, I came to something like "Search for an individual" (and then "Search by Lookup ID" for the other type). I wonder if it's something where it would make sense to have a headline and then a little more info in explainer text, e.g.,

**Search for an individual**
Enter the required information below to see if an individual is already receiving benefits in another state

**Search by Lookup ID**
Enter a lookup ID below to retrieve the corresponding individual's information

??

**Comment by juliaklindpaintner** [comment]
Tagging @erinzstrenio here as well to lend her expertise!

**Comment by heymatthenry** [comment]
I like "Search for an individual." Or perhaps "Search SNAP participants"?

**Comment by juliaklindpaintner** [comment]
I like that! It reinforces that this is specifically for SNAP and that's
what you're doing: trying to see if this person is already a SNAP
participant.

__


Julia Lindpaintner (she/her)

18F <https://18f.gsa.gov/> | Technology Transformation Service
<http://www.gsa.gov/portal/category/25729>

General Services Administration (GSA)
<http://www.gsa.gov/portal/category/100000>

312.813.7727 | ***@***.***

Follow 18F on Twitter <https://twitter.com/18F>

**Comment by erinzstrenio** [comment]
I agree on "Search for SNAP participants" 

@cjhskippy had also suggested "Search for active SNAP participation" which is another good option, but I wonder if there'd ever be a scenario where the NAC shows a SNAP participant with a non-active status, so might be best to leave "active" out.

**Comment by cjhskippy** [comment]
Messaged Suzy in Teams to get the :gavel: for "Search for SNAP participants". Good call y'all.

**Comment by cjhskippy** [comment]
Search for SNAP participants is approved.  Nice call @heymatthenry !
