### ISSUE TITLE
Integrate `create-apim` into `create-resources`

### ISSUE THREAD

**Issue by kingcomma** [18F/piipan#617]
Now that `configure-easy-auth` is part of `create-resources`, the [IaC documentation](https://github.com/18F/piipan/blob/main/docs/iac.md) calls for an order of operations that will result in an error. Specifically, `create-resources` will try and operate on APIM resources that will not exist until `create-apim` is run.

Running `create-apim` from within `create-resources` will solve this issue. This will require adding a means for passing the email argument required by `create-apim`.

**Comment by ryanhofdotgov** [comment]
Looks like this is resolved with #678 and #758
