### ISSUE TITLE
Finalize Quickstart Development Guide for State Distribution

### ISSUE THREAD

**Issue by echappen** [18F/piipan#623]
We've added a rough draft of the Quickstart guide to the repo and are adding links to it as documentation for each endpoint is developed. Before we share it with states, we'll need to:

- check with our partner about what level of detail we can present about development/production environments
- Consider how we present the match, lookup id, status APIs a single unified API. The fact they are 3 separate Function Apps is an implementation detail that shouldn't drive the documentation I think.
- Have a nice OpenAPI generated set of HTML documentation to link to.
  - Only needs to include query + lookup ID APIs at this time
  - At sprint review, note current status of bulk upload docs in case follow-up work is needed.

**Comment by echappen** [comment]
> Have a nice OpenAPI generated set of HTML documentation to link to

@kingcomma @ryanhofdotgov I'm trying to remember our Eng Sync convo about this:
1. What would ideal access to this site look like? Can it be publicly available as long as it's not interactive?
1. Did we rule out using APIM's own [developer portal](https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-developer-portal) for API documentation?

**Comment by ryanhofdotgov** [comment]
There might be a short term and long term solution here. Short term constraints:
* nothing in our TTS Azure subscription can be exposed without authentication
* Federalist or Markdown in Github (not GitHub Pages) are really the only ATO'd solutions at TTS at our disposal for publishing web pages to the public
* nothing in our partner's subscription can be exposed outside it's agency until it has an ATO

**Comment by echappen** [comment]
Given these constraints, the short-term solution I'm envisioning would be plopping our generated OpenApi yaml files into a [federalist-uswds-jekyll](https://github.com/18F/federalist-uswds-jekyll) repo, styling it kind of [like this](https://robertlove.github.io/jekyll-openapi/) (also from a Jekyll [repo](https://github.com/robertlove/jekyll-openapi)) and hosting it on Federalist. Does that sound like a good path forward?

**Comment by kingcomma** [comment]
I wonder if there is an even shorter-term solution where the specs are rendered to markdown rather than HTML? Something like [swagger-markdown](https://www.npmjs.com/package/swagger-markdown) (haven't looked into this too much).

**Comment by ryanhofdotgov** [comment]
Either option sounds good – goal is just to spend a minimum amount of styling work to make it usable to send out to states sooner rather than later and look like something you'd expect when learning an API for the 1st time (i.e., not just raw YAML).

We can iterate on it as we expand stable API.

**Comment by echappen** [comment]
The suggestion from @kingcomma would be a lighter lift so I'll go with that for now. FYI this is what a swagger-markdown generated file looks like. It doesn't look like there's any configuration of the markdown available.

<img width="680" alt="Screen Shot 2021-04-13 at 11 41 13 AM" src="https://user-images.githubusercontent.com/4267629/114589530-607aaf80-9c4d-11eb-8d34-ecbc7a207343.png">

<img width="555" alt="Screen Shot 2021-04-13 at 11 41 18 AM" src="https://user-images.githubusercontent.com/4267629/114590035-e0087e80-9c4d-11eb-9105-f48ac5466f9a.png">

**Comment by echappen** [comment]
I also found the [redoc-cli](https://github.com/Redocly/redoc/blob/master/cli/README.md#redoc-cli) which can generate a zero-dependency html file with pretty nice styling. We just kept this file in our repo and linked to the "view file" version, could this be an option? 

<img width="1437" alt="Screen Shot 2021-04-13 at 1 59 33 PM" src="https://user-images.githubusercontent.com/4267629/114606633-1d2a3c00-9c61-11eb-98b3-8d1f3abed84e.png">

**Comment by ryanhofdotgov** [comment]
Interesting – I didn't know that was possible. Do you have an example link?

**Comment by echappen** [comment]
Ah I suppose you can't—I was confusing viewing a raw file in Github with a "View File in Browser" capability. Viewing it in Github would only show the source code, unless you use something like [htmlpreview.github.com](https://github.com/htmlpreview/htmlpreview.github.com)
