### ISSUE TITLE
Lookup API provides querying state

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#628]
As a state agency worker responsible for processing match results, I want to know which state to contact when I am notified of a match that was initiated by another state's query.

AC:
- [ ] Lookup API returns the state that initiated the match related to that match ID

Depends on #683

**Comment by echappen** [comment]
@cjhskippy @ryanhofdotgov Can you confirm this is the workflow we're solving for here?

Workflow:
1. EW is notified of a match; receives a Lookup ID
2. EW performs lookup ID request; receives PII from original request
3. EW takes that PII and performs a Match query; receives match data that includes the match records for their state and 1-to-N number of records from other states

If there's only one other state in the match response, then this state is the one to be contacted. 

If there are multiple other states, then it's ambiguous which state performed the original match query. Including the state in the response for step 2 above will make this clear and possibly save an extra step for the EW.

Do I have this right?

**Comment by cjhskippy** [comment]
Closed in connection with removal of Lookup API.
