### ISSUE TITLE
Codify Database Private Link setup into iac script

### ISSUE THREAD

**Issue by echappen** [18F/piipan#659]
Based on what we learned in #11, we will need to change the iac script in order to establish a private connection from participant-records database to the Azure resources that connect to it:

- [ ] Shift state Match resources to same resource group as participant-records DB (rg-core)
- [ ] Upgrade all function apps that need to talk to participant-records DB to P1V2 sku from Standard
- [ ] Create VNet and Private Endpoint resources in `participant-records.json` ARM template
- [ ] Disable public access and access to all azure resources on DB programmatically (not sure if this can be done in ARM template or will have to be done in CLI or portal)
- [ ] In state function app template, integrate with same VNet created above programmatically (ARM template would be ideal)
- [ ] In match function app template, integrate with same VNet above programmatically (ARM template would be ideal)

**Comment by echappen** [comment]
@kingcomma @ryanhofdotgov Moving state match function apps into rg-core will cause a name conflict with the etl function apps.

Based on our [naming conventions](https://github.com/18F/piipan/blob/dfa37755de66f4b06460ca2a62644a34e0125231/docs/azure-naming-conventions.md) I propose changing the names of these resources to something like this (using `ea` state as an example:

| resource | name |
|---|---|
| Etl function app | func-ea-etl-dev |
| Etl function app storage account | stor-ea-etl-dev |
| Match function app | func-ea-match-dev |
| Match function app storage account | stor-ea-match-dev |

Does this look good to you?

_Context on why we're moving these resources into the same resource group is that private endpoints are only private when talking to resources within the same resource group._

**Comment by ryanhofdotgov** [comment]
That looks good, modulo storage accounts not allowing hyphens in its name and we will need the apps and the storage accounts to support PREFIX in its name.

**Comment by echappen** [comment]
Thanks! Updated:

| resource | name |
|---|---|
| Etl function app | fns-func-ea-etl-dev |
| Etl function app storage account | fnsstoreaetldev |
| Match function app | fns-func-ea-match-dev |
| Match function app storage account | fnsstoreamatchdev |

**Comment by kingcomma** [comment]
Looks good to me too, including @ryanhofdotgov's comments.

**Comment by ryanhofdotgov** [comment]
@echappen Just double-checking, but all the check list items on this ticket have been done and we can close this issue?

**Comment by echappen** [comment]
Yep!
