### ISSUE TITLE
Apply naming conventions to IaC

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#660]
When https://github.com/18F/piipan/pull/451 is closed, sweep through the IaC, updating resource naming conventions to match [azure-naming-conventions.md](https://github.com/18F/piipan/blob/main/docs/azure-naming-conventions.md).

Purge and recreate all resource groups for `dev` from scratch when IaC changes complete.

**Comment by ryanhofdotgov** [comment]
At the same time, swap in `tts` for `PREFIX` in `iac/env/tts/dev.bash`.

**Comment by echappen** [comment]
Convo here on how to determine naming scope: https://github.com/18F/piipan/pull/679#issuecomment-818764365

**Comment by ryanhofdotgov** [comment]
@echappen Took a look at https://drive.google.com/file/d/10rdGCeh3gG8F_34GOJ6CG7-nYkaFjqYt/view:
- what does the asterisk on some of the Globals denote?
- shorten `PREFIX-psql-participant-records-ENV` to `PREFIX-psql-participants-ENV`?
- rename `PREFIX-kv-secret-keeper-ENV` to `PREFIX-kv-core-ENV`?
- as we use dash for a name delimeter, I'd change `PREFIX-app-query-tool-ENV` to `PREFIX-app-querytool-ENV`
- likewise for `PREFIX-fd-query-tool-ENV` (and we've already sent off the name to get a cert) 

It doesn't have to happen this round, but I am imagining that the orchestrator Function App will get renamed to something more general as we pile more Functions into it. Likewise, the metrics database will probably cease to just be metrics.

Not sure if this was intending to be complete, but we have also have the APIM instances as well as the managed identities.

**Comment by echappen** [comment]
Forgot to mention: asterisk refers to [this note about web app scope](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftweb)

I wanted to ask about the participant-records database: given that we may be keeping lookup ID in there too, should we change the name to something more general than `participants`?

The rest of your items look good to me. I'll add APIM and Managed Identities to the doc as well.

**Comment by echappen** [comment]
A markdown file was a bad way to share this on my part. Here's a better [csv of all the names](https://docs.google.com/spreadsheets/d/1Ry4vzX4SfHjOvrCkfy97WnUN9glWWq5wXG0v0PsF8CQ/edit?usp=sharing).

Updated:
- PSQL Database server
- Key Vault
- Query Tool Web App
- Query Tool Front Door
- Metrics PSQL Database Server

Added:
- API Management Service
- Per-State managed identities

**Comment by ryanhofdotgov** [comment]
@echappen I was thinking the look up id would go into the metrics database cluster, but just in a separate logical database:
https://github.com/18F/piipan/issues/701#issuecomment-821526098
i.e., look up id will get stored along with collaboration data, as we start rolling that in. And collab data doesn't likely need a whole other database cluster.

Data retention policies can be more easily implemented at the cluster level and the bulk PII has data retention need of only a few days, while all the collab data, look up id data, needs much longer.

**Comment by echappen** [comment]
Thanks for clarifying. I struggled to think of a generalized name for the Metrics database server. I changed it to `secondary`.

**Comment by ryanhofdotgov** [comment]
We are in bikeshed territory here, but in the database world "secondary" has been used in the context of database replication (e.g., [MySQL](https://dev.mysql.com/doc/refman/5.7/en/group-replication-primary-secondary-replication.html), [Informix](https://www.ibm.com/docs/en/informix-servers/12.10/12.10?topic=replication-primary-secondary-database-servers)).

It's not very descriptive, but we could use the `core` moniker we've been using elsewhere. Other random ideas: 'umbrella', 'potpourri', 'omni', 'platform'.

**Comment by echappen** [comment]
Good point, I'll go with `core` then to keep consistent.

**Comment by echappen** [comment]
Added a few more things to the csv:
- participants database private endpoint
- per-state event grid topics and subscriptions

**Comment by ryanhofdotgov** [comment]
Looks good! A couple of nitpicks:

For `snet-psql-pe-ENV`, we will need different names for the subnets for the different db clusters.

How about `evgs-` for event subscriptions? That seems slightly more consistent with what Microsoft has been doing with other event resources. I've opened up an [issue for Microsoft documentation team](https://github.com/MicrosoftDocs/cloud-adoption-framework/issues/454).
