### ISSUE TITLE
Add Metrics Resources to Virtual Network

### ISSUE THREAD

**Issue by echappen** [18F/piipan#691]
We want to block Metrics data and resources from the public internet, but want to keep it communicable with the Dashboard app. 

- [X] Move Metrics resources into core resource group
  - [X] add a Systype tag for metrics
- [x] Bump up pricing plan on metrics db to same as participants, to prep for private link creation
- [x] Create new subnet on existing VNet for metrics private link
- [x] For Metrics DB: create private link, private dns zone, and link private DNS zone to VNet (same routine as what’s in participant-records arm template)
- [x] Add Metrics function apps to same app service plan as other function apps already on VNet
- [x] Delegate Metrics function apps to VNet and existing function app subnet
- [x] Disable public access and access to all azure resources on Metrics DB programmatically (can use remove-external-network.bash for this)
- [ ] Re-run full iac script with these changes
- [ ] Confirm it all works
  - [ ] On Bulk Upload event, Metrics Collect app can insert records into metrics DB
  - [ ] Metrics API can show records from Metrics DB
  - [ ] Dashboard app can display items from Metrics API

**Comment by cjhskippy** [comment]
Noting that per discussion today, a subset of these tasks may be separable into the MVP while others may be optional for initial launch.
