### ISSUE TITLE
Move Orchestrator Function App to Private Network

### ISSUE THREAD

**Issue by echappen** [18F/piipan#694]
We'd like to move the orchestrator function app into our existing Virtual Network while keeping connections open from the Query Tool App.

Based on some preliminary research and past work with VNets, this would entail:

1. Moving the orchestrator function app from the match resource group into the core resource group where the VNet resides
1. Placing the orchestrator function app onto the same App Service Plan (Premium - P1V2) as the function apps already on the VNet because 1) a premium plan is necessary for VNet integration and 2) we can save money with a single premium plan over two
1. Delegating orchestrator app to the function app subnet within the VNet 
1. Codifying all of this into our iac routine 

Verify that query tool app can still access the orchestrator API once this is complete.

**Comment by ryanhofdotgov** [comment]
As you think about how app service plans get structured, you want to think about CPU utilization, and the mix of high and low usage jobs, and when they occur.

It might be better to move the orchestrator, dashboard, and query tool into the same app service plan, if possible. Assuming we need web apps moved to a premium plan (didn't see that in the 3 tickets you just opened). Orchestrator will have high usage 6am-9pm ET, but query tool and dashboard will have relatively low usage.

Orchestrator and per-state match API usage are always happening in simultaneously; they are guaranteed to always be fighting for the same underlying CPU resources in the app service plan. And one orchestrator-level request spawns 50 per-state match requests, so more likelihood of different scaling needs. 

Metrics App Service plan could be come a catch all for all the rest of the system's low use Function Apps. Perhaps except for the batch-oriented function app workloads involving the state databases that have workloads in the off peak times.

**Comment by ryanhofdotgov** [comment]
Another thing we may have to consider sooner rather than later is whether to have different app plan configurations depending on the environment to save costs. e.g., in dev and test shove everything we can into a single app plan, and only separate them for pre-prod/prod.

**Comment by kingcomma** [comment]
@echappen and @ryanhofdotgov Can you validate this set of acceptance criteria for this issue? My current plan is to put the orchestrator into the same subnet and app service plan as the other function apps (ETL, per-state matching, metrics API, metrics collector). I see this as the "get everything into the vnet" step that can be followed by an "optimize app service plan usage" step as needed.

This also leaves the orchestrator Function in `rg-match-` for now and defers the decision to drop that resource group entirely.

- [ ] Move orchestrator to the `plan-apps1-$ENV` App Service Plan
- [ ] Add orchestrator to the `snet-apps1-$ENV` subnet within the core vnet
- [ ] Confirm query tool and duplicate participation API management instance can connect to orchestrator

**Comment by echappen** [comment]
These criteria lgtm. I'd also be up for making a decision now rather than later on whether we keep the `rg-match-` group, since removing another resource group would speed up IAC.

**Comment by ryanhofdotgov** [comment]
LGTM, keeping in mind that at this point the primary motivation of establishing the VNet is to be able to control network egress for the Function Apps, and then to possibly incorporate private endpoints on them.

I think we can collapse the match resource group into core at some point, but I am only expecting maybe a few dozen seconds shaved off over IaC run time?
