### ISSUE TITLE
Use PostgreSQL in place of Table Storage for lookup API

### ISSUE THREAD

**Issue by kingcomma** [18F/piipan#701]
As a developer, I want a database solution for the lookup API that fits within our existing architecture and does not increase cognitive load by introducing new tools and approaches.

As a system owner, I want a database solution with automated backups (which are not available using Table Storage).

Task consists of:
- [ ] Create a new database within the `core` cluster and bind it to the orchestrator as part of the IaC process
- [ ] Update orchestrator to use the new database for storing and retrieving lookup IDs
- [x] Quick ADR write-up, why we thought table records were a good quick start, why we changed to our default RDBMS.

**Comment by ryanhofdotgov** [comment]
@kingcomma I think actually we want to leave the participant-records db cluster as is, to more strictly isolate the bulk PII. Instead elevate the metrics db cluster to a catch-all/"core" cluster.

I anticipate using it with separate databases for:
* metrics
* lookup API
* to be determined status API
* to be determined collaboration work

As backup retention policy is set at the cluster level, this keeps databases with similar retention needs together.

**Comment by ryanhofdotgov** [comment]
Added ADR as part of task (but can be split off as necessary)

**Comment by cjhskippy** [comment]
Closed in connection with removal of Lookup API.
