### ISSUE TITLE
Only match against last name

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#708]
Partner has repeatedly commented that matching algorithm should be exact match on last name, dob, ssn. 

Looks like relevant line that needs to be changed is in [Api.cs](https://github.com/18F/piipan/blob/b4cfcbde31c718628ec3813c21a3f2b929274dcc/match/src/Piipan.Match.State/Api.cs#L100)

**Comment by kingcomma** [comment]
The required property on [Piipan.Match.Orchestrator.MatchQuery.FirstName](https://github.com/18F/piipan/blob/main/match/src/Piipan.Match.Orchestrator/MatchRequest.cs#L22) and [Piipan.QueryTool.PiiRecord](https://github.com/18F/piipan/blob/main/query-tool/src/Piipan.QueryTool/PiiRecord.cs) will also need to be removed.

**Comment by cjhskippy** [comment]
When this is done, we can also close #541 as a duplicate.
