### ISSUE TITLE
Update `env/tts/dev.bash` to use `tts` PREFIX

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#753]
Update `env/tts/dev.bash` to use `tts` PREFIX, just like `env/tts/test.bash`. Will need to update CircleCI build files. 

Should completely delete resources in the resource groups and then re-run create-resources.bash.

**Comment by echappen** [comment]
Resolved in this [PR](https://github.com/18F/piipan/pull/763)
