### ISSUE TITLE
ETL process for bulk PII

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#8]
Implement Extract-Transform-Load process for bulk PII, working against the format defined in #3, and publishing to the database schema defined in #2. 

This story just covers basic capabilities.  More comprehensive bulk upload behavior is covered in issue #41

AC:
- [x] Webservice will accept a small, correctly-formatted CSV
- [x] If the input file is valid, web service replaces all records in the database for the appropriate state.

**Comment by cjhskippy** [comment]
Making a note to myself... if noting "vulnerable" individuals wasn't a part of this CSV, I'll want to add a follow-on ticket for next sprint to capture that data point as well.

**Comment by ryanhofdotgov** [comment]
@cjhskippy There's a free-form text placeholder field/column called `exception` in the CSV and database schemas. General idea is that we may not know the exact range of values at this early stage, but if any value was present at all, we could at least show that and have conditional logic on it.
