### ISSUE TITLE
Reject SSNs that are defined as invalid by the SSN

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#805]
The bulk upload ETL process should reject PII records that have invalid SSN according to the SSA. See https://secure.ssa.gov/poms.nsf/lnx/0110201035

The state agencies should already be rejecting these, so don't expect this to be triggered very often.

Consider only enabling in pre-prod and production, so we can use invalid SSNs in our test data. Or perhaps just designate a portion of the invalid number space for that.

**Comment by cjhskippy** [comment]
This can be closed.  It's not applicable now that the NAC accepts deidentified participant information.
