### ISSUE TITLE
Don't show time in DOB in query tool results

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#827]
Query tool results show a timestamp in the DOB field, but that's not necessary and can be removed:

<img width="500" alt="Screen Shot 2021-05-12 at 9 30 55 AM" src="https://user-images.githubusercontent.com/37100189/118011351-c6b62900-b304-11eb-8aa0-1b3b3eaaf209.png">

**Comment by kingcomma** [comment]
@ryanhofdotgov Have we determined a uniform approach to date formats for display in our UIs? I'm wondering if it's safe to assume an EW will interpret a date string as `month/day/year`? Or would `04/04/1913` be ambiguous and something like `April 04, 1913` would be preferred?

**Comment by ryanhofdotgov** [comment]
We should ask the state users, but in my experience government form fields in US are overwhelmingly MM/DD/YYYY, and that's what the EWs would expect and is probably preferred when eyeballing/comparing data. So it is a good default IMHO absent specific feedback.
