### ISSUE TITLE
Track final benefits date when assigned

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#860]
As a State agency worker, I want to see final date for which a participant received benefits when viewing a match so that I can avoid contacting another state or the applicant when the rules allow it.

If an applicant has closed their case in another state but their last benefits date has not yet passed, the eligibility worker in the initiating state should be able to pro-rate benefits to begin after that terminal date without having to perform further review.  Similarly, the worker should also be able to avoid taking action on a disclosure by the participant that they were previously receiving benefits in that state.

AC:
- [ ] Bulk upload process allows optional inclusion of final benefit date
- [ ] Bulk upload accepts records without last benefit date
- [ ] ~~Query API returns the final benefit date in the matched state(s) when provided~~

**Comment by echappen** [comment]
@cjhskippy @ryanhofdotgov Wanted to confirm the naming of this field. I'd like to name it `benefits_end_date` in the database and API's. ("final benefits date" seemed more ambiguous.)

**Comment by ryanhofdotgov** [comment]
That makes sense to me. I'd also like to check if this is a month (`04/2021`) or a specific day (`04/28/2021`)

**Comment by echappen** [comment]
My 2 Cents is that the flexibility we get from date outweighs the simplicity of month. It also avoids the system ever having evaluate a cutoff date based only on month.

**Comment by ryanhofdotgov** [comment]
I think that's how the SNAP program works though (month by month), but not 100% sure. That's why we can talk about getting the 3 most recent benefit months, since benefits across the states are handled on month to month basis.

If SNAP is strictly month by month (not by end of date) and we require a full date to be provided, then all the state systems will have to determine the last day of every month (handle leap years, etc.) when they submit their data.

**Comment by echappen** [comment]
Ah, ok. What do you think is the best way to clarify that? Is this something we should ask states about in our calls next week?

**Comment by ryanhofdotgov** [comment]
I think our engagement partners at FNS/SNAP should be able to answer, but states could probably answer too.
