### ISSUE TITLE
Website Lookup includes case number and identifier

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#867]
As a State Agency worker, I want to be able to look up the correct person when someone from another state sends me a Lookup ID related to a match.  Our user research has indicated that workers can more quickly find the correct person when they have access to the case number.

Using the web portal to access the information associated with a Lookup ID should provide the same information as is returned by the API.  See #866

**Comment by kingcomma** [comment]
@echappen I don't think there is a separate issue specific to just the Lookup API response, but noting that for the case/participant identifiers to show up in lookup results on the query tool website, the query/match API will need to accept those fields in API requests. Those requests are serialized to JSON which is stored in the lookup database and returned via the lookup API.

Related to your question in https://github.com/18F/piipan/issues/866#issuecomment-844228848

**Comment by echappen** [comment]
> for the case/participant identifiers to show up in lookup results on the query tool website, the query/match API will need to accept those fields in API requests

Good point @kingcomma. It seems strange to ask for case ID and participant ID in a query request if the system won't actually be using it in the query. I'm not sure how to solve for that.

**Comment by kingcomma** [comment]
We've somewhat already set that precedent by requiring `first` but not yet using it in the match algorithm.

That said, re-reading this ticket, I think there's a discrepancy: The lookup API will return the information in the API *request* not the information returned from the API (as written).

@cjhskippy Maybe we need some clarification on this ticket?

**Comment by cjhskippy** [comment]
Closed in connection with removal of Lookup API.
