### ISSUE TITLE
Query website includes final benefit date

### ISSUE THREAD

**Issue by cjhskippy** [18F/piipan#868]
Update the query website to include the same information added to the API in #860

AC:
- [ ] Query responses that include a match also provide the final benefit date

**Comment by cjhskippy** [comment]
This looks partially implemented - the row exists in the table, but it isn't getting populated (example: Carri 
Farrington in the sample data set)

**Comment by ryanhofdotgov** [comment]
It's working for me on tts/dev:

<img width="600" alt="Screen Shot 2021-06-14 at 8 47 49 AM" src="https://user-images.githubusercontent.com/37100189/121920814-414fdb00-cced-11eb-815c-ad859177b374.png">

Any chance you were looking on tts/test? The [PR that implemented this feature](https://github.com/18F/piipan/pull/911) is was closed at the start of this sprint, so it won't be on tts/test until after this sprint closes.

**Comment by cjhskippy** [comment]
Curious.  I was looking at it on dev.  I had the window still open from Friday, but will retry shortly:

<img width="1031" alt="Screen Shot 2021-06-14 at 11 02 06 AM" src="https://user-images.githubusercontent.com/1299543/121938054-35b9df80-cd00-11eb-9500-4ce86a334374.png">

**Comment by ryanhofdotgov** [comment]
That is a little unsettling 🤔

**Comment by cjhskippy** [comment]
Huh.  Seems to be working just fine now.  Made a few tries with variations on that name, worked every time.  I guess it's time to close this.
