### ISSUE TITLE
Create a quickstart guide for new developers

### ISSUE THREAD

**Issue by timoballard** [18F/piipan#877]
Create a quickstart document for onboarding new developers. Ideally, this document will:
 - Guide new engineers through the process of setting up their local development environment
 - Provide non-technical, narrative explanation of Piipan components and their relationships
 - Link to detailed technical documentation for specific components where relevant

- [x] 18F dev tests steps recommended in guide to verify that they work without errors.

**Comment by cjhskippy** [comment]
@edwintorres verified the steps and the guide has been shared in Teams.
