### ISSUE TITLE
Add state username to duplicate participation API

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#889]
The near real-time APIs are designed to be incorporated into a state backoffice system and triggered by actions by a state eligibility worker. (This is in contrast to the bulk upload API, which is intended to be automated).

To support cross-organizational auditing (AU-16), extend the DupPart API to include a field for the state system to supply the state worker username on whose behalf they are making the query for. Make it optional – states SHOULD specify the username, not MUST.

AC:
- [ ] States can provide the username to match query API calls
~~States can provide username to lookup API calls~~ no longer needed since lookup API is going away
- [ ] Username for match API is forwarded to audit logs
- [ ] API documentation is updated

**Comment by echappen** [comment]
@ryanhofdotgov I'm assuming we'd want to accept strings like email addresses as a username. Are there any characters/patterns we'd want to reject?

**Comment by ryanhofdotgov** [comment]
Accepting the printable ASCII range is usually a safe bet.

**Comment by echappen** [comment]
@ryanhofdotgov @cjhskippy Putting the question above another way—do we want only emails for this field, or can it be any text? (e.g. "eleni", "echappen", "Eleni Chappen", "noreply@tts.test")

**Comment by ryanhofdotgov** [comment]
It can be any text, as we don't know how the states might structure their usernames.
