### ISSUE TITLE
Configure appropriate redundancy setting for storage accounts that back Function Apps

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#892]
- [ ] Explore https://docs.microsoft.com/en-us/azure/storage/common/storage-disaster-recovery-guidance
- [ ] It is preferred to have identical redundancy settings across dev/test/pre-prod/prod, but if it is cost prohibitive, allow redundancy setting to be environment specific.

Focus here I believe should be on availability benefits within a zone rather than geo-redundancy across regions, as Function Apps can be re-created at will.

**Comment by edwintorres** [comment]
@ryanhofdotgov the zone redundancy is not yet available on Azure Gov according to [the documentation](https://docs.microsoft.com/en-us/azure/azure-government/compare-azure-government-global-azure#azure-managed-disks).

Given that Function Apps can be re-created at will. The Standard_LRS should be ok for this.
