### ISSUE TITLE
Remove state_name from duplicate participation API query response

### ISSUE THREAD

**Issue by kingcomma** [18F/piipan#895]
Keep only `state_abbr`. Goal is to normalize response data and reduce response size.

**Comment by kingcomma** [comment]
@ryanhofdotgov @echappen What do you think about changing `state_abbr` to `state` while we are at it? The `_abbr` suffix was really only a product of also having `state_name` in the response.

**Comment by ryanhofdotgov** [comment]
I like the esthetics of that. Is it easy enough to add `state`, and keep `state_abbr` around for a couple of sprints to allow early integrators to catch up?

**Comment by kingcomma** [comment]
Yep, should be a trivial update to `Piipan.Match.State/MatchResponse.cs` and `Piipan.Match.Orchestrator/MatchResponse.cs`.
