### ISSUE TITLE
Query API returns the most recent benefit months

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#897]
As a state agency worker, I want to know if an applicant received benefits in another state where they recently resided so that I can make an accurate determination of whether they are eligible in my state.

This may be relevant for a non-head-of-household in a still-open case. For example, a child who spends some time with out-of-state relatives or shared custody.

Note that we believe all state agencies use the same definition of "benefit month" - that is, it's not necessary to track the specific days, we can say "June 2020" and it should mean the same thing for eligibility dates across all states.

AC:
For each match returned by the query API:
- [ ] The response indicates whether the participant received benefits within each of the most recent 3 months.
- [ ] Specify in the response which months are covered (Example: February 2021, March 2021, April 2021)

Related to #861 - that's the same feature implemented in bulk uploads.

**Comment by cjhskippy** [comment]
Added the AC that we should explicitly name which months are covered.  An API consumer can't infer the "last 3 months" based on today's date - they'd have to know when the other state uploaded their bulk data (was the upload before or after the end of the month?)

**Comment by echappen** [comment]
@ryanhofdotgov How do we want to represent this data in the database? Would it just remain the human-readable text provided by states, or would we convert each into a date?

**Comment by ryanhofdotgov** [comment]
Let's store it as a native database date field – this allows easier time-based SQL queries against the data set. Not that I think we anticipate that right now – it's just the most natural approach.

**Comment by ryanhofdotgov** [comment]
More specifically, with this approach, we would model it as a table column that is an array of dates.

**Comment by echappen** [comment]
@ryanhofdotgov @cjhskippy  For the JSON response, I'm thinking we'd represent recent benefit months as an array of strings. Each item would be the same ISO year-month format as `benefits_end_month`. Does that sound good?

example:
```
recent_benefit_months: ["2021-04", "2021-03", "2021-02"]
```

**Comment by ryanhofdotgov** [comment]
Sounds good – I would explicitly sort the dates in descending order at the API level and document that in the API spec.
