### ISSUE TITLE
Update CodeClimate, CodeQL for new dev/main branches

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#901]
CodeClimate, CodeQL doesn't seem to be executing on PRs any more. Likely related to main branch -> dev rename, and new main branch.

**Comment by kingcomma** [comment]
CodeClimate is updated: [Dashboard](https://codeclimate.com/github/18F/piipan) > Repo Settings > Default branch

**Comment by ryanhofdotgov** [comment]
CodeQL resolved in #934
