### ISSUE TITLE
UX recommendations for NAC website

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/piipan#914]
Revisit this post-pivot: Make suggestions for improvements to the front-end experience of the query tool and dashboard app
See also issue #890 

- [x] Create list of suggested UX/design changes for 
  - [x] query tool
  - [x] metrics dashboard
- [x] Prioritize suggested changes
- [x] Cross-reference with #1013 
- [x] Create mockups as needed

**Comment by ryanhofdotgov** [comment]
Also looking for some guidance on how the lookup ID form should be linked from the main query tool page, some type of nav bar?
And perhaps a UI mechanism to easily look for current matches against PII that the Lookup ID returns. Keeping in mind, that right now, every time match is searched for and found, you'll get a new (different) Lookup ID.

**Comment by juliaklindpaintner** [comment]
Recommendations are [summarized here](https://docs.google.com/document/d/1vdjSyvKMzKIqyZ0JM3QAlv_3X3NfLSPjGwVIi2D00y8/edit#) with screenshots.

**Comment by juliaklindpaintner** [comment]
@ryanhofdotgov Addressed the nav between query and lookup tool in my recommendations linked above. 

I haven't had a chance to address the UI mechanism that looks for current matches against the PII that the Lookup ID returns, but I added that to my running list in #890

**Comment by juliaklindpaintner** [comment]
Reopening this issue to reassess post-pivot
