### ISSUE TITLE
piipan CSV column names shouldn't contain spaces

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#935]
CSV libraries, tools, and custom code don't have a good reputation for handling spaces in column names:
https://www.google.com/search?q=csv+column+names+spaces

The recently added columns for case id, participants id, benefit end month, recent benefit months, etc. should be altered to have an underscore instead of a space.

**Comment by ryanhofdotgov** [comment]
@echappen Any chance you would be able to pick this issue up before the end of sprint?

**Comment by echappen** [comment]
yep!
