### ISSUE TITLE
Update local dev instructions to reflect environment variables need to be set

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/piipan#952]
When I run the query tool locally, it throws an exception. Had to:
```
export OrchApiUri="https://foo.local"
```
to get it to work. I suspect other components (dashboard, function apps, etc.) might need updated documentation for similar reasons.

**Comment by cjhskippy** [comment]
Triaged as important for MVP, but not immediate.  Hope to postpone this as long as we can, but still do it before the next developer onboards.

**Comment by ryanhofdotgov** [comment]
These little things should really be addressed as we find them, so that at any given time, someone can checkout the code and run it locally (where applicable). This task shouldn't take more than 1-2 hours.

**Comment by timoballard** [comment]
Verified that the dashboard runs as expected locally after following [documented local development instructions](https://github.com/18F/tock/blob/3e1d2e0ed214718950707936ce97c9fcd2a4eb3a/bin/run.sh#L11)

**Comment by timoballard** [comment]
Added `Local development` section to metrics readme
